package helper

var langEn = map[int]string{
	100: "Continue",
	101: "Switching Protocols",
	102: "Processing",
	200: "OK",
	201: "Created",
	202: "Accepted",
	203: "Non-Authoritative Information",
	204: "No Content",
	205: "Reset Content",
	206: "Partial Content",
	207: "Multi-Status",
	208: "Already Reported",
	226: "IM Used",
	300: "Multiple Choices",
	301: "Moved Permanently",
	302: "Found",
	303: "See Other",
	304: "Not Modified",
	305: "Use Proxy",
	307: "Temporary Redirect",
	308: "Permanent Redirect",
	400: "Bad Request",
	401: "Unauthorized",
	402: "Payment Required",
	403: "Forbidden",
	404: "Not Found",
	405: "Method Not Allowed",
	406: "Not Acceptable",
	407: "Proxy Authentication Required",
	408: "Request Timeout",
	409: "Conflict",
	410: "Gone",
	411: "Length Required",
	412: "Precondition Failed",
	413: "Payload Too Large",
	414: "URI Too Long",
	415: "Unsupported Media Type",
	416: "Range Not Satisfiable",
	417: "Expectation Failed",
	418: "I'm a teapot",
	419: "Session Has Expired",
	421: "Misdirected Request",
	422: "Unprocessable Entity",
	423: "Locked",
	424: "Failed Dependency",
	425: "Too Early",
	426: "Upgrade Required",
	428: "Precondition Required",
	429: "Too Many Requests",
	431: "Request Header Fields Too Large",
	444: "Connection Closed Without Response",
	449: "Retry With",
	451: "Unavailable For Legal Reasons",
	499: "Client Closed Request",
	500: "Internal Server Error",
	501: "Not Implemented",
	502: "Bad Gateway",
	503: "Maintenance Mode",
	504: "Gateway Timeout",
	505: "HTTP Version Not Supported",
	506: "Variant Also Negotiates",
	507: "Insufficient Storage",
	508: "Loop Detected",
	509: "Bandwidth Limit Exceeded",
	510: "Not Extended",
	511: "Network Authentication Required",
	520: "Unknown Error",
	521: "Web Server is Down",
	522: "Connection Timed Out",
	523: "Origin Is Unreachable",
	524: "A Timeout Occurred",
	525: "SSL Handshake Failed",
	526: "Invalid SSL Certificate",
	527: "Railgun Error",
	598: "Network Read Timeout Error",
	599: "Network Connect Timeout Error",
}

var langId = map[int]string{
	100: "Lanjutkan",
	101: "Beralih Protokol",
	102: "Memproses",
	200: "OK",
	201: "Dibuat",
	202: "Diterima",
	203: "Informasi Non-Authoritative",
	204: "Tidak Ada Konten",
	205: "Reset Konten",
	206: "Konten Sebagian",
	207: "Multi-Status",
	208: "Sudah Dilaporkan",
	226: "IM Digunakan",
	300: "Pilihan Ganda",
	301: "Dialihkan Permanen",
	302: "Ditemukan",
	303: "Lihat Lainnya",
	304: "Tidak Dimodifikasi",
	305: "Gunakan Proxy",
	307: "Pengalihan Sementara",
	308: "Pengalihan Permanen",
	400: "Permintaan Tidak Valid",
	401: "Tidak Diizinkan",
	402: "Diperlukan Pembayaran",
	403: "Dilarang",
	404: "Tidak Ditemukan",
	405: "Metode Tidak Diizinkan",
	406: "Tidak Dapat Diterima",
	407: "Diperlukan Otentikasi Proxy",
	408: "Waktu Permintaan Habis",
	409: "Konflik",
	410: "Sudah Tidak Ada",
	411: "Diperlukan Panjang",
	412: "Keadaan Awal Gagal",
	413: "Payload Terlalu Besar",
	414: "URI Terlalu Panjang",
	415: "Tipe Media Tidak Didukung",
	416: "Rentang Tidak Memuaskan",
	417: "Gagal Harapan",
	418: "Saya adalah Teko",
	419: "Sesi Telah Kadaluarsa",
	421: "Permintaan Salah Alamat",
	422: "Entitas Tidak Dapat Diproses",
	423: "Terkunci",
	424: "Ketergantungan Gagal",
	425: "Terlalu Awal",
	426: "Diperlukan Peningkatan",
	428: "Diperlukan Pra-Syarat",
	429: "Terlalu Banyak Permintaan",
	431: "Bidang Header Permintaan Terlalu Besar",
	444: "Koneksi Ditutup Tanpa Respons",
	449: "Coba Lagi Dengan",
	451: "Tidak Tersedia Untuk Alasan Hukum",
	499: "Klien Menutup Permintaan",
	500: "Kesalahan Server Internal",
	501: "Belum Diimplementasikan",
	502: "Gerbang Buruk",
	503: "Mode Pemeliharaan",
	504: "Waktu Tunggu Gerbang",
	505: "Versi HTTP Tidak Didukung",
	506: "Variasi Juga Menegosiasikan",
	507: "Penyimpanan Tidak Cukup",
	508: "Deteksi Lingkaran",
	509: "Limit Bandwidth Terlampaui",
	510: "Tidak Diperluas",
	511: "Otentikasi Jaringan Diperlukan",
	520: "Kesalahan Tidak Dikenal",
	521: "Server Web Mati",
	522: "Waktu Tunggu Koneksi Habis",
	523: "Asal Tidak Dapat Diakses",
	524: "Waktu Tunggu Habis",
	525: "SSL Handshake Gagal",
	526: "Sertifikat SSL Tidak Valid",
	527: "Kesalahan Railgun",
	598: "Kesalahan Baca Jaringan Timeout",
	599: "Kesalahan Koneksi Jaringan Timeout",
}

func HttpMessage(lang string, code int) string {
	var response string

	switch lang {
	case "en":
		response = langEn[code]
	default:
		response = langId[code]
	}

	return response
}
